server:
   port: 9000
   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: localhost
    preferIpAddress: false
    

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.gateway: DEBUG

spring:
   application:
    name: auth
   datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
   jpa:
    hibernate:
      ddl-auto: none
    show-sql: true